// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionOnFailure string

const (
	ActionOnFailure_CANCEL_AND_WAIT    ActionOnFailure = "CANCEL_AND_WAIT"
	ActionOnFailure_CONTINUE           ActionOnFailure = "CONTINUE"
	ActionOnFailure_TERMINATE_CLUSTER  ActionOnFailure = "TERMINATE_CLUSTER"
	ActionOnFailure_TERMINATE_JOB_FLOW ActionOnFailure = "TERMINATE_JOB_FLOW"
)

type AdjustmentType string

const (
	AdjustmentType_CHANGE_IN_CAPACITY         AdjustmentType = "CHANGE_IN_CAPACITY"
	AdjustmentType_EXACT_CAPACITY             AdjustmentType = "EXACT_CAPACITY"
	AdjustmentType_PERCENT_CHANGE_IN_CAPACITY AdjustmentType = "PERCENT_CHANGE_IN_CAPACITY"
)

type AuthMode string

const (
	AuthMode_IAM AuthMode = "IAM"
	AuthMode_SSO AuthMode = "SSO"
)

type AutoScalingPolicyState string

const (
	AutoScalingPolicyState_ATTACHED  AutoScalingPolicyState = "ATTACHED"
	AutoScalingPolicyState_ATTACHING AutoScalingPolicyState = "ATTACHING"
	AutoScalingPolicyState_DETACHED  AutoScalingPolicyState = "DETACHED"
	AutoScalingPolicyState_DETACHING AutoScalingPolicyState = "DETACHING"
	AutoScalingPolicyState_FAILED    AutoScalingPolicyState = "FAILED"
	AutoScalingPolicyState_PENDING   AutoScalingPolicyState = "PENDING"
)

type AutoScalingPolicyStateChangeReasonCode string

const (
	AutoScalingPolicyStateChangeReasonCode_CLEANUP_FAILURE   AutoScalingPolicyStateChangeReasonCode = "CLEANUP_FAILURE"
	AutoScalingPolicyStateChangeReasonCode_PROVISION_FAILURE AutoScalingPolicyStateChangeReasonCode = "PROVISION_FAILURE"
	AutoScalingPolicyStateChangeReasonCode_USER_REQUEST      AutoScalingPolicyStateChangeReasonCode = "USER_REQUEST"
)

type CancelStepsRequestStatus string

const (
	CancelStepsRequestStatus_FAILED    CancelStepsRequestStatus = "FAILED"
	CancelStepsRequestStatus_SUBMITTED CancelStepsRequestStatus = "SUBMITTED"
)

type ClusterState string

const (
	ClusterState_BOOTSTRAPPING          ClusterState = "BOOTSTRAPPING"
	ClusterState_RUNNING                ClusterState = "RUNNING"
	ClusterState_STARTING               ClusterState = "STARTING"
	ClusterState_TERMINATED             ClusterState = "TERMINATED"
	ClusterState_TERMINATED_WITH_ERRORS ClusterState = "TERMINATED_WITH_ERRORS"
	ClusterState_TERMINATING            ClusterState = "TERMINATING"
	ClusterState_WAITING                ClusterState = "WAITING"
)

type ClusterStateChangeReasonCode string

const (
	ClusterStateChangeReasonCode_ALL_STEPS_COMPLETED    ClusterStateChangeReasonCode = "ALL_STEPS_COMPLETED"
	ClusterStateChangeReasonCode_BOOTSTRAP_FAILURE      ClusterStateChangeReasonCode = "BOOTSTRAP_FAILURE"
	ClusterStateChangeReasonCode_INSTANCE_FAILURE       ClusterStateChangeReasonCode = "INSTANCE_FAILURE"
	ClusterStateChangeReasonCode_INSTANCE_FLEET_TIMEOUT ClusterStateChangeReasonCode = "INSTANCE_FLEET_TIMEOUT"
	ClusterStateChangeReasonCode_INTERNAL_ERROR         ClusterStateChangeReasonCode = "INTERNAL_ERROR"
	ClusterStateChangeReasonCode_STEP_FAILURE           ClusterStateChangeReasonCode = "STEP_FAILURE"
	ClusterStateChangeReasonCode_USER_REQUEST           ClusterStateChangeReasonCode = "USER_REQUEST"
	ClusterStateChangeReasonCode_VALIDATION_ERROR       ClusterStateChangeReasonCode = "VALIDATION_ERROR"
)

type ComparisonOperator string

const (
	ComparisonOperator_GREATER_THAN          ComparisonOperator = "GREATER_THAN"
	ComparisonOperator_GREATER_THAN_OR_EQUAL ComparisonOperator = "GREATER_THAN_OR_EQUAL"
	ComparisonOperator_LESS_THAN             ComparisonOperator = "LESS_THAN"
	ComparisonOperator_LESS_THAN_OR_EQUAL    ComparisonOperator = "LESS_THAN_OR_EQUAL"
)

type ComputeLimitsUnitType string

const (
	ComputeLimitsUnitType_InstanceFleetUnits ComputeLimitsUnitType = "InstanceFleetUnits"
	ComputeLimitsUnitType_Instances          ComputeLimitsUnitType = "Instances"
	ComputeLimitsUnitType_VCPU               ComputeLimitsUnitType = "VCPU"
)

type ExecutionEngineType string

const (
	ExecutionEngineType_EMR ExecutionEngineType = "EMR"
)

type IDCUserAssignment string

const (
	IDCUserAssignment_OPTIONAL IDCUserAssignment = "OPTIONAL"
	IDCUserAssignment_REQUIRED IDCUserAssignment = "REQUIRED"
)

type IdentityType string

const (
	IdentityType_GROUP IdentityType = "GROUP"
	IdentityType_USER  IdentityType = "USER"
)

type InstanceCollectionType string

const (
	InstanceCollectionType_INSTANCE_FLEET InstanceCollectionType = "INSTANCE_FLEET"
	InstanceCollectionType_INSTANCE_GROUP InstanceCollectionType = "INSTANCE_GROUP"
)

type InstanceFleetState string

const (
	InstanceFleetState_BOOTSTRAPPING InstanceFleetState = "BOOTSTRAPPING"
	InstanceFleetState_PROVISIONING  InstanceFleetState = "PROVISIONING"
	InstanceFleetState_RECONFIGURING InstanceFleetState = "RECONFIGURING"
	InstanceFleetState_RESIZING      InstanceFleetState = "RESIZING"
	InstanceFleetState_RUNNING       InstanceFleetState = "RUNNING"
	InstanceFleetState_SUSPENDED     InstanceFleetState = "SUSPENDED"
	InstanceFleetState_TERMINATED    InstanceFleetState = "TERMINATED"
	InstanceFleetState_TERMINATING   InstanceFleetState = "TERMINATING"
)

type InstanceFleetStateChangeReasonCode string

const (
	InstanceFleetStateChangeReasonCode_CLUSTER_TERMINATED InstanceFleetStateChangeReasonCode = "CLUSTER_TERMINATED"
	InstanceFleetStateChangeReasonCode_INSTANCE_FAILURE   InstanceFleetStateChangeReasonCode = "INSTANCE_FAILURE"
	InstanceFleetStateChangeReasonCode_INTERNAL_ERROR     InstanceFleetStateChangeReasonCode = "INTERNAL_ERROR"
	InstanceFleetStateChangeReasonCode_VALIDATION_ERROR   InstanceFleetStateChangeReasonCode = "VALIDATION_ERROR"
)

type InstanceFleetType string

const (
	InstanceFleetType_CORE   InstanceFleetType = "CORE"
	InstanceFleetType_MASTER InstanceFleetType = "MASTER"
	InstanceFleetType_TASK   InstanceFleetType = "TASK"
)

type InstanceGroupState string

const (
	InstanceGroupState_ARRESTED      InstanceGroupState = "ARRESTED"
	InstanceGroupState_BOOTSTRAPPING InstanceGroupState = "BOOTSTRAPPING"
	InstanceGroupState_ENDED         InstanceGroupState = "ENDED"
	InstanceGroupState_PROVISIONING  InstanceGroupState = "PROVISIONING"
	InstanceGroupState_RECONFIGURING InstanceGroupState = "RECONFIGURING"
	InstanceGroupState_RESIZING      InstanceGroupState = "RESIZING"
	InstanceGroupState_RUNNING       InstanceGroupState = "RUNNING"
	InstanceGroupState_SHUTTING_DOWN InstanceGroupState = "SHUTTING_DOWN"
	InstanceGroupState_SUSPENDED     InstanceGroupState = "SUSPENDED"
	InstanceGroupState_TERMINATED    InstanceGroupState = "TERMINATED"
	InstanceGroupState_TERMINATING   InstanceGroupState = "TERMINATING"
)

type InstanceGroupStateChangeReasonCode string

const (
	InstanceGroupStateChangeReasonCode_CLUSTER_TERMINATED InstanceGroupStateChangeReasonCode = "CLUSTER_TERMINATED"
	InstanceGroupStateChangeReasonCode_INSTANCE_FAILURE   InstanceGroupStateChangeReasonCode = "INSTANCE_FAILURE"
	InstanceGroupStateChangeReasonCode_INTERNAL_ERROR     InstanceGroupStateChangeReasonCode = "INTERNAL_ERROR"
	InstanceGroupStateChangeReasonCode_VALIDATION_ERROR   InstanceGroupStateChangeReasonCode = "VALIDATION_ERROR"
)

type InstanceGroupType string

const (
	InstanceGroupType_CORE   InstanceGroupType = "CORE"
	InstanceGroupType_MASTER InstanceGroupType = "MASTER"
	InstanceGroupType_TASK   InstanceGroupType = "TASK"
)

type InstanceRoleType string

const (
	InstanceRoleType_CORE   InstanceRoleType = "CORE"
	InstanceRoleType_MASTER InstanceRoleType = "MASTER"
	InstanceRoleType_TASK   InstanceRoleType = "TASK"
)

type InstanceState string

const (
	InstanceState_AWAITING_FULFILLMENT InstanceState = "AWAITING_FULFILLMENT"
	InstanceState_BOOTSTRAPPING        InstanceState = "BOOTSTRAPPING"
	InstanceState_PROVISIONING         InstanceState = "PROVISIONING"
	InstanceState_RUNNING              InstanceState = "RUNNING"
	InstanceState_TERMINATED           InstanceState = "TERMINATED"
)

type InstanceStateChangeReasonCode string

const (
	InstanceStateChangeReasonCode_BOOTSTRAP_FAILURE  InstanceStateChangeReasonCode = "BOOTSTRAP_FAILURE"
	InstanceStateChangeReasonCode_CLUSTER_TERMINATED InstanceStateChangeReasonCode = "CLUSTER_TERMINATED"
	InstanceStateChangeReasonCode_INSTANCE_FAILURE   InstanceStateChangeReasonCode = "INSTANCE_FAILURE"
	InstanceStateChangeReasonCode_INTERNAL_ERROR     InstanceStateChangeReasonCode = "INTERNAL_ERROR"
	InstanceStateChangeReasonCode_VALIDATION_ERROR   InstanceStateChangeReasonCode = "VALIDATION_ERROR"
)

type JobFlowExecutionState string

const (
	JobFlowExecutionState_BOOTSTRAPPING JobFlowExecutionState = "BOOTSTRAPPING"
	JobFlowExecutionState_COMPLETED     JobFlowExecutionState = "COMPLETED"
	JobFlowExecutionState_FAILED        JobFlowExecutionState = "FAILED"
	JobFlowExecutionState_RUNNING       JobFlowExecutionState = "RUNNING"
	JobFlowExecutionState_SHUTTING_DOWN JobFlowExecutionState = "SHUTTING_DOWN"
	JobFlowExecutionState_STARTING      JobFlowExecutionState = "STARTING"
	JobFlowExecutionState_TERMINATED    JobFlowExecutionState = "TERMINATED"
	JobFlowExecutionState_WAITING       JobFlowExecutionState = "WAITING"
)

type LogType string

const (
	LogType_application_logs   LogType = "application-logs"
	LogType_persistent_ui_logs LogType = "persistent-ui-logs"
	LogType_system_logs        LogType = "system-logs"
)

type LogUploadPolicyValue string

const (
	LogUploadPolicyValue_disabled           LogUploadPolicyValue = "disabled"
	LogUploadPolicyValue_emr_managed        LogUploadPolicyValue = "emr-managed"
	LogUploadPolicyValue_on_customer_s3only LogUploadPolicyValue = "on-customer-s3only"
)

type MarketType string

const (
	MarketType_ON_DEMAND MarketType = "ON_DEMAND"
	MarketType_SPOT      MarketType = "SPOT"
)

type NotebookExecutionStatus string

const (
	NotebookExecutionStatus_FAILED        NotebookExecutionStatus = "FAILED"
	NotebookExecutionStatus_FAILING       NotebookExecutionStatus = "FAILING"
	NotebookExecutionStatus_FINISHED      NotebookExecutionStatus = "FINISHED"
	NotebookExecutionStatus_FINISHING     NotebookExecutionStatus = "FINISHING"
	NotebookExecutionStatus_RUNNING       NotebookExecutionStatus = "RUNNING"
	NotebookExecutionStatus_STARTING      NotebookExecutionStatus = "STARTING"
	NotebookExecutionStatus_START_PENDING NotebookExecutionStatus = "START_PENDING"
	NotebookExecutionStatus_STOPPED       NotebookExecutionStatus = "STOPPED"
	NotebookExecutionStatus_STOPPING      NotebookExecutionStatus = "STOPPING"
	NotebookExecutionStatus_STOP_PENDING  NotebookExecutionStatus = "STOP_PENDING"
)

type OnClusterAppUIType string

const (
	OnClusterAppUIType_ApplicationMaster   OnClusterAppUIType = "ApplicationMaster"
	OnClusterAppUIType_JobHistoryServer    OnClusterAppUIType = "JobHistoryServer"
	OnClusterAppUIType_ResourceManager     OnClusterAppUIType = "ResourceManager"
	OnClusterAppUIType_SparkHistoryServer  OnClusterAppUIType = "SparkHistoryServer"
	OnClusterAppUIType_TezUI               OnClusterAppUIType = "TezUI"
	OnClusterAppUIType_YarnTimelineService OnClusterAppUIType = "YarnTimelineService"
)

type OnDemandCapacityReservationPreference string

const (
	OnDemandCapacityReservationPreference_none OnDemandCapacityReservationPreference = "none"
	OnDemandCapacityReservationPreference_open OnDemandCapacityReservationPreference = "open"
)

type OnDemandCapacityReservationUsageStrategy string

const (
	OnDemandCapacityReservationUsageStrategy_use_capacity_reservations_first OnDemandCapacityReservationUsageStrategy = "use-capacity-reservations-first"
)

type OnDemandProvisioningAllocationStrategy string

const (
	OnDemandProvisioningAllocationStrategy_lowest_price OnDemandProvisioningAllocationStrategy = "lowest-price"
	OnDemandProvisioningAllocationStrategy_prioritized  OnDemandProvisioningAllocationStrategy = "prioritized"
)

type OutputNotebookFormat string

const (
	OutputNotebookFormat_HTML OutputNotebookFormat = "HTML"
)

type PersistentAppUIType string

const (
	PersistentAppUIType_SHS PersistentAppUIType = "SHS"
	PersistentAppUIType_TEZ PersistentAppUIType = "TEZ"
	PersistentAppUIType_YTS PersistentAppUIType = "YTS"
)

type PlacementGroupStrategy string

const (
	PlacementGroupStrategy_CLUSTER   PlacementGroupStrategy = "CLUSTER"
	PlacementGroupStrategy_NONE      PlacementGroupStrategy = "NONE"
	PlacementGroupStrategy_PARTITION PlacementGroupStrategy = "PARTITION"
	PlacementGroupStrategy_SPREAD    PlacementGroupStrategy = "SPREAD"
)

type ProfilerType string

const (
	ProfilerType_SHS   ProfilerType = "SHS"
	ProfilerType_TEZUI ProfilerType = "TEZUI"
	ProfilerType_YTS   ProfilerType = "YTS"
)

type ReconfigurationType string

const (
	ReconfigurationType_MERGE     ReconfigurationType = "MERGE"
	ReconfigurationType_OVERWRITE ReconfigurationType = "OVERWRITE"
)

type RepoUpgradeOnBoot string

const (
	RepoUpgradeOnBoot_NONE     RepoUpgradeOnBoot = "NONE"
	RepoUpgradeOnBoot_SECURITY RepoUpgradeOnBoot = "SECURITY"
)

type ScaleDownBehavior string

const (
	ScaleDownBehavior_TERMINATE_AT_INSTANCE_HOUR   ScaleDownBehavior = "TERMINATE_AT_INSTANCE_HOUR"
	ScaleDownBehavior_TERMINATE_AT_TASK_COMPLETION ScaleDownBehavior = "TERMINATE_AT_TASK_COMPLETION"
)

type ScalingStrategy string

const (
	ScalingStrategy_ADVANCED ScalingStrategy = "ADVANCED"
	ScalingStrategy_DEFAULT  ScalingStrategy = "DEFAULT"
)

type SessionState string

const (
	SessionState_BUSY        SessionState = "BUSY"
	SessionState_FAILED      SessionState = "FAILED"
	SessionState_IDLE        SessionState = "IDLE"
	SessionState_STARTED     SessionState = "STARTED"
	SessionState_STARTING    SessionState = "STARTING"
	SessionState_SUBMITTED   SessionState = "SUBMITTED"
	SessionState_TERMINATED  SessionState = "TERMINATED"
	SessionState_TERMINATING SessionState = "TERMINATING"
)

type SpotProvisioningAllocationStrategy string

const (
	SpotProvisioningAllocationStrategy_capacity_optimized             SpotProvisioningAllocationStrategy = "capacity-optimized"
	SpotProvisioningAllocationStrategy_capacity_optimized_prioritized SpotProvisioningAllocationStrategy = "capacity-optimized-prioritized"
	SpotProvisioningAllocationStrategy_diversified                    SpotProvisioningAllocationStrategy = "diversified"
	SpotProvisioningAllocationStrategy_lowest_price                   SpotProvisioningAllocationStrategy = "lowest-price"
	SpotProvisioningAllocationStrategy_price_capacity_optimized       SpotProvisioningAllocationStrategy = "price-capacity-optimized"
)

type SpotProvisioningTimeoutAction string

const (
	SpotProvisioningTimeoutAction_SWITCH_TO_ON_DEMAND SpotProvisioningTimeoutAction = "SWITCH_TO_ON_DEMAND"
	SpotProvisioningTimeoutAction_TERMINATE_CLUSTER   SpotProvisioningTimeoutAction = "TERMINATE_CLUSTER"
)

type Statistic string

const (
	Statistic_AVERAGE      Statistic = "AVERAGE"
	Statistic_MAXIMUM      Statistic = "MAXIMUM"
	Statistic_MINIMUM      Statistic = "MINIMUM"
	Statistic_SAMPLE_COUNT Statistic = "SAMPLE_COUNT"
	Statistic_SUM          Statistic = "SUM"
)

type StepCancellationOption string

const (
	StepCancellationOption_SEND_INTERRUPT    StepCancellationOption = "SEND_INTERRUPT"
	StepCancellationOption_TERMINATE_PROCESS StepCancellationOption = "TERMINATE_PROCESS"
)

type StepExecutionState string

const (
	StepExecutionState_CANCELLED   StepExecutionState = "CANCELLED"
	StepExecutionState_COMPLETED   StepExecutionState = "COMPLETED"
	StepExecutionState_CONTINUE    StepExecutionState = "CONTINUE"
	StepExecutionState_FAILED      StepExecutionState = "FAILED"
	StepExecutionState_INTERRUPTED StepExecutionState = "INTERRUPTED"
	StepExecutionState_PENDING     StepExecutionState = "PENDING"
	StepExecutionState_RUNNING     StepExecutionState = "RUNNING"
)

type StepState string

const (
	StepState_CANCELLED      StepState = "CANCELLED"
	StepState_CANCEL_PENDING StepState = "CANCEL_PENDING"
	StepState_COMPLETED      StepState = "COMPLETED"
	StepState_FAILED         StepState = "FAILED"
	StepState_INTERRUPTED    StepState = "INTERRUPTED"
	StepState_PENDING        StepState = "PENDING"
	StepState_RUNNING        StepState = "RUNNING"
)

type StepStateChangeReasonCode string

const (
	StepStateChangeReasonCode_NONE StepStateChangeReasonCode = "NONE"
)

type Unit string

const (
	Unit_BITS                  Unit = "BITS"
	Unit_BITS_PER_SECOND       Unit = "BITS_PER_SECOND"
	Unit_BYTES                 Unit = "BYTES"
	Unit_BYTES_PER_SECOND      Unit = "BYTES_PER_SECOND"
	Unit_COUNT                 Unit = "COUNT"
	Unit_COUNT_PER_SECOND      Unit = "COUNT_PER_SECOND"
	Unit_GIGA_BITS             Unit = "GIGA_BITS"
	Unit_GIGA_BITS_PER_SECOND  Unit = "GIGA_BITS_PER_SECOND"
	Unit_GIGA_BYTES            Unit = "GIGA_BYTES"
	Unit_GIGA_BYTES_PER_SECOND Unit = "GIGA_BYTES_PER_SECOND"
	Unit_KILO_BITS             Unit = "KILO_BITS"
	Unit_KILO_BITS_PER_SECOND  Unit = "KILO_BITS_PER_SECOND"
	Unit_KILO_BYTES            Unit = "KILO_BYTES"
	Unit_KILO_BYTES_PER_SECOND Unit = "KILO_BYTES_PER_SECOND"
	Unit_MEGA_BITS             Unit = "MEGA_BITS"
	Unit_MEGA_BITS_PER_SECOND  Unit = "MEGA_BITS_PER_SECOND"
	Unit_MEGA_BYTES            Unit = "MEGA_BYTES"
	Unit_MEGA_BYTES_PER_SECOND Unit = "MEGA_BYTES_PER_SECOND"
	Unit_MICRO_SECONDS         Unit = "MICRO_SECONDS"
	Unit_MILLI_SECONDS         Unit = "MILLI_SECONDS"
	Unit_NONE                  Unit = "NONE"
	Unit_PERCENT               Unit = "PERCENT"
	Unit_SECONDS               Unit = "SECONDS"
	Unit_TERA_BITS             Unit = "TERA_BITS"
	Unit_TERA_BITS_PER_SECOND  Unit = "TERA_BITS_PER_SECOND"
	Unit_TERA_BYTES            Unit = "TERA_BYTES"
	Unit_TERA_BYTES_PER_SECOND Unit = "TERA_BYTES_PER_SECOND"
)
