//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingPolicyStateChangeReason) DeepCopyInto(out *AutoScalingPolicyStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingPolicyStateChangeReason.
func (in *AutoScalingPolicyStateChangeReason) DeepCopy() *AutoScalingPolicyStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(AutoScalingPolicyStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockPublicAccessConfiguration) DeepCopyInto(out *BlockPublicAccessConfiguration) {
	*out = *in
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockPublicAccessConfiguration.
func (in *BlockPublicAccessConfiguration) DeepCopy() *BlockPublicAccessConfiguration {
	if in == nil {
		return nil
	}
	out := new(BlockPublicAccessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockPublicAccessConfigurationMetadata) DeepCopyInto(out *BlockPublicAccessConfigurationMetadata) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockPublicAccessConfigurationMetadata.
func (in *BlockPublicAccessConfigurationMetadata) DeepCopy() *BlockPublicAccessConfigurationMetadata {
	if in == nil {
		return nil
	}
	out := new(BlockPublicAccessConfigurationMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancelStepsInfo) DeepCopyInto(out *CancelStepsInfo) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancelStepsInfo.
func (in *CancelStepsInfo) DeepCopy() *CancelStepsInfo {
	if in == nil {
		return nil
	}
	out := new(CancelStepsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchAlarmDefinition) DeepCopyInto(out *CloudWatchAlarmDefinition) {
	*out = *in
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchAlarmDefinition.
func (in *CloudWatchAlarmDefinition) DeepCopy() *CloudWatchAlarmDefinition {
	if in == nil {
		return nil
	}
	out := new(CloudWatchAlarmDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchLogConfiguration) DeepCopyInto(out *CloudWatchLogConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogGroupName != nil {
		in, out := &in.LogGroupName, &out.LogGroupName
		*out = new(string)
		**out = **in
	}
	if in.LogStreamNamePrefix != nil {
		in, out := &in.LogStreamNamePrefix, &out.LogStreamNamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchLogConfiguration.
func (in *CloudWatchLogConfiguration) DeepCopy() *CloudWatchLogConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudWatchLogConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	if in.AutoScalingRole != nil {
		in, out := &in.AutoScalingRole, &out.AutoScalingRole
		*out = new(string)
		**out = **in
	}
	if in.LogEncryptionKMSKeyID != nil {
		in, out := &in.LogEncryptionKMSKeyID, &out.LogEncryptionKMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
	if in.MasterPublicDNSName != nil {
		in, out := &in.MasterPublicDNSName, &out.MasterPublicDNSName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OSReleaseLabel != nil {
		in, out := &in.OSReleaseLabel, &out.OSReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.RequestedAMIVersion != nil {
		in, out := &in.RequestedAMIVersion, &out.RequestedAMIVersion
		*out = new(string)
		**out = **in
	}
	if in.RunningAMIVersion != nil {
		in, out := &in.RunningAMIVersion, &out.RunningAMIVersion
		*out = new(string)
		**out = **in
	}
	if in.SecurityConfiguration != nil {
		in, out := &in.SecurityConfiguration, &out.SecurityConfiguration
		*out = new(string)
		**out = **in
	}
	if in.ServiceRole != nil {
		in, out := &in.ServiceRole, &out.ServiceRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStateChangeReason) DeepCopyInto(out *ClusterStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStateChangeReason.
func (in *ClusterStateChangeReason) DeepCopy() *ClusterStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(ClusterStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSummary) DeepCopyInto(out *ClusterSummary) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSummary.
func (in *ClusterSummary) DeepCopy() *ClusterSummary {
	if in == nil {
		return nil
	}
	out := new(ClusterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTimeline) DeepCopyInto(out *ClusterTimeline) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTimeline.
func (in *ClusterTimeline) DeepCopy() *ClusterTimeline {
	if in == nil {
		return nil
	}
	out := new(ClusterTimeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Command) DeepCopyInto(out *Command) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ScriptPath != nil {
		in, out := &in.ScriptPath, &out.ScriptPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Command.
func (in *Command) DeepCopy() *Command {
	if in == nil {
		return nil
	}
	out := new(Command)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSBlockDevice) DeepCopyInto(out *EBSBlockDevice) {
	*out = *in
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSBlockDevice.
func (in *EBSBlockDevice) DeepCopy() *EBSBlockDevice {
	if in == nil {
		return nil
	}
	out := new(EBSBlockDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSVolume) DeepCopyInto(out *EBSVolume) {
	*out = *in
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.VolumeID != nil {
		in, out := &in.VolumeID, &out.VolumeID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSVolume.
func (in *EBSVolume) DeepCopy() *EBSVolume {
	if in == nil {
		return nil
	}
	out := new(EBSVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EC2InstanceAttributes) DeepCopyInto(out *EC2InstanceAttributes) {
	*out = *in
	if in.EC2AvailabilityZone != nil {
		in, out := &in.EC2AvailabilityZone, &out.EC2AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.EC2KeyName != nil {
		in, out := &in.EC2KeyName, &out.EC2KeyName
		*out = new(string)
		**out = **in
	}
	if in.EC2SubnetID != nil {
		in, out := &in.EC2SubnetID, &out.EC2SubnetID
		*out = new(string)
		**out = **in
	}
	if in.EmrManagedMasterSecurityGroup != nil {
		in, out := &in.EmrManagedMasterSecurityGroup, &out.EmrManagedMasterSecurityGroup
		*out = new(string)
		**out = **in
	}
	if in.EmrManagedSlaveSecurityGroup != nil {
		in, out := &in.EmrManagedSlaveSecurityGroup, &out.EmrManagedSlaveSecurityGroup
		*out = new(string)
		**out = **in
	}
	if in.IAMInstanceProfile != nil {
		in, out := &in.IAMInstanceProfile, &out.IAMInstanceProfile
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccessSecurityGroup != nil {
		in, out := &in.ServiceAccessSecurityGroup, &out.ServiceAccessSecurityGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EC2InstanceAttributes.
func (in *EC2InstanceAttributes) DeepCopy() *EC2InstanceAttributes {
	if in == nil {
		return nil
	}
	out := new(EC2InstanceAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorDetail) DeepCopyInto(out *ErrorDetail) {
	*out = *in
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = new(string)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorDetail.
func (in *ErrorDetail) DeepCopy() *ErrorDetail {
	if in == nil {
		return nil
	}
	out := new(ErrorDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureDetails) DeepCopyInto(out *FailureDetails) {
	*out = *in
	if in.LogFile != nil {
		in, out := &in.LogFile, &out.LogFile
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureDetails.
func (in *FailureDetails) DeepCopy() *FailureDetails {
	if in == nil {
		return nil
	}
	out := new(FailureDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HadoopJarStepConfig) DeepCopyInto(out *HadoopJarStepConfig) {
	*out = *in
	if in.Jar != nil {
		in, out := &in.Jar, &out.Jar
		*out = new(string)
		**out = **in
	}
	if in.MainClass != nil {
		in, out := &in.MainClass, &out.MainClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HadoopJarStepConfig.
func (in *HadoopJarStepConfig) DeepCopy() *HadoopJarStepConfig {
	if in == nil {
		return nil
	}
	out := new(HadoopJarStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HadoopStepConfig) DeepCopyInto(out *HadoopStepConfig) {
	*out = *in
	if in.Jar != nil {
		in, out := &in.Jar, &out.Jar
		*out = new(string)
		**out = **in
	}
	if in.MainClass != nil {
		in, out := &in.MainClass, &out.MainClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HadoopStepConfig.
func (in *HadoopStepConfig) DeepCopy() *HadoopStepConfig {
	if in == nil {
		return nil
	}
	out := new(HadoopStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	if in.InstanceGroupID != nil {
		in, out := &in.InstanceGroupID, &out.InstanceGroupID
		*out = new(string)
		**out = **in
	}
	if in.PrivateDNSName != nil {
		in, out := &in.PrivateDNSName, &out.PrivateDNSName
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPAddress != nil {
		in, out := &in.PrivateIPAddress, &out.PrivateIPAddress
		*out = new(string)
		**out = **in
	}
	if in.PublicDNSName != nil {
		in, out := &in.PublicDNSName, &out.PublicDNSName
		*out = new(string)
		**out = **in
	}
	if in.PublicIPAddress != nil {
		in, out := &in.PublicIPAddress, &out.PublicIPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFleetStateChangeReason) DeepCopyInto(out *InstanceFleetStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFleetStateChangeReason.
func (in *InstanceFleetStateChangeReason) DeepCopy() *InstanceFleetStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(InstanceFleetStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFleetTimeline) DeepCopyInto(out *InstanceFleetTimeline) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFleetTimeline.
func (in *InstanceFleetTimeline) DeepCopy() *InstanceFleetTimeline {
	if in == nil {
		return nil
	}
	out := new(InstanceFleetTimeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGroup) DeepCopyInto(out *InstanceGroup) {
	*out = *in
	if in.BidPrice != nil {
		in, out := &in.BidPrice, &out.BidPrice
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGroup.
func (in *InstanceGroup) DeepCopy() *InstanceGroup {
	if in == nil {
		return nil
	}
	out := new(InstanceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGroupDetail) DeepCopyInto(out *InstanceGroupDetail) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.LastStateChangeReason != nil {
		in, out := &in.LastStateChangeReason, &out.LastStateChangeReason
		*out = new(string)
		**out = **in
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
	if in.StartDateTime != nil {
		in, out := &in.StartDateTime, &out.StartDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGroupDetail.
func (in *InstanceGroupDetail) DeepCopy() *InstanceGroupDetail {
	if in == nil {
		return nil
	}
	out := new(InstanceGroupDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGroupStateChangeReason) DeepCopyInto(out *InstanceGroupStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGroupStateChangeReason.
func (in *InstanceGroupStateChangeReason) DeepCopy() *InstanceGroupStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(InstanceGroupStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGroupTimeline) DeepCopyInto(out *InstanceGroupTimeline) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGroupTimeline.
func (in *InstanceGroupTimeline) DeepCopy() *InstanceGroupTimeline {
	if in == nil {
		return nil
	}
	out := new(InstanceGroupTimeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStateChangeReason) DeepCopyInto(out *InstanceStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStateChangeReason.
func (in *InstanceStateChangeReason) DeepCopy() *InstanceStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(InstanceStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTimeline) DeepCopyInto(out *InstanceTimeline) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTimeline.
func (in *InstanceTimeline) DeepCopy() *InstanceTimeline {
	if in == nil {
		return nil
	}
	out := new(InstanceTimeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobFlowDetail) DeepCopyInto(out *JobFlowDetail) {
	*out = *in
	if in.AutoScalingRole != nil {
		in, out := &in.AutoScalingRole, &out.AutoScalingRole
		*out = new(string)
		**out = **in
	}
	if in.JobFlowRole != nil {
		in, out := &in.JobFlowRole, &out.JobFlowRole
		*out = new(string)
		**out = **in
	}
	if in.LogEncryptionKMSKeyID != nil {
		in, out := &in.LogEncryptionKMSKeyID, &out.LogEncryptionKMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
	if in.ServiceRole != nil {
		in, out := &in.ServiceRole, &out.ServiceRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobFlowDetail.
func (in *JobFlowDetail) DeepCopy() *JobFlowDetail {
	if in == nil {
		return nil
	}
	out := new(JobFlowDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobFlowExecutionStatusDetail) DeepCopyInto(out *JobFlowExecutionStatusDetail) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.LastStateChangeReason != nil {
		in, out := &in.LastStateChangeReason, &out.LastStateChangeReason
		*out = new(string)
		**out = **in
	}
	if in.ReadyDateTime != nil {
		in, out := &in.ReadyDateTime, &out.ReadyDateTime
		*out = (*in).DeepCopy()
	}
	if in.StartDateTime != nil {
		in, out := &in.StartDateTime, &out.StartDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobFlowExecutionStatusDetail.
func (in *JobFlowExecutionStatusDetail) DeepCopy() *JobFlowExecutionStatusDetail {
	if in == nil {
		return nil
	}
	out := new(JobFlowExecutionStatusDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobFlowInstancesDetail) DeepCopyInto(out *JobFlowInstancesDetail) {
	*out = *in
	if in.MasterInstanceID != nil {
		in, out := &in.MasterInstanceID, &out.MasterInstanceID
		*out = new(string)
		**out = **in
	}
	if in.MasterPublicDNSName != nil {
		in, out := &in.MasterPublicDNSName, &out.MasterPublicDNSName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobFlowInstancesDetail.
func (in *JobFlowInstancesDetail) DeepCopy() *JobFlowInstancesDetail {
	if in == nil {
		return nil
	}
	out := new(JobFlowInstancesDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValue) DeepCopyInto(out *KeyValue) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValue.
func (in *KeyValue) DeepCopy() *KeyValue {
	if in == nil {
		return nil
	}
	out := new(KeyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDimension) DeepCopyInto(out *MetricDimension) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDimension.
func (in *MetricDimension) DeepCopy() *MetricDimension {
	if in == nil {
		return nil
	}
	out := new(MetricDimension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookExecution) DeepCopyInto(out *NotebookExecution) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.LastStateChangeReason != nil {
		in, out := &in.LastStateChangeReason, &out.LastStateChangeReason
		*out = new(string)
		**out = **in
	}
	if in.NotebookParams != nil {
		in, out := &in.NotebookParams, &out.NotebookParams
		*out = new(string)
		**out = **in
	}
	if in.OutputNotebookURI != nil {
		in, out := &in.OutputNotebookURI, &out.OutputNotebookURI
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookExecution.
func (in *NotebookExecution) DeepCopy() *NotebookExecution {
	if in == nil {
		return nil
	}
	out := new(NotebookExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookExecutionSummary) DeepCopyInto(out *NotebookExecutionSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.ExecutionEngineID != nil {
		in, out := &in.ExecutionEngineID, &out.ExecutionEngineID
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookExecutionSummary.
func (in *NotebookExecutionSummary) DeepCopy() *NotebookExecutionSummary {
	if in == nil {
		return nil
	}
	out := new(NotebookExecutionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSRelease) DeepCopyInto(out *OSRelease) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSRelease.
func (in *OSRelease) DeepCopy() *OSRelease {
	if in == nil {
		return nil
	}
	out := new(OSRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentAppUI) DeepCopyInto(out *PersistentAppUI) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
	if in.LastStateChangeReason != nil {
		in, out := &in.LastStateChangeReason, &out.LastStateChangeReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentAppUI.
func (in *PersistentAppUI) DeepCopy() *PersistentAppUI {
	if in == nil {
		return nil
	}
	out := new(PersistentAppUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementType) DeepCopyInto(out *PlacementType) {
	*out = *in
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementType.
func (in *PlacementType) DeepCopy() *PlacementType {
	if in == nil {
		return nil
	}
	out := new(PlacementType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseLabelFilter) DeepCopyInto(out *ReleaseLabelFilter) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseLabelFilter.
func (in *ReleaseLabelFilter) DeepCopy() *ReleaseLabelFilter {
	if in == nil {
		return nil
	}
	out := new(ReleaseLabelFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3MonitoringConfiguration) DeepCopyInto(out *S3MonitoringConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3MonitoringConfiguration.
func (in *S3MonitoringConfiguration) DeepCopy() *S3MonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(S3MonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingRule) DeepCopyInto(out *ScalingRule) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingRule.
func (in *ScalingRule) DeepCopy() *ScalingRule {
	if in == nil {
		return nil
	}
	out := new(ScalingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptBootstrapActionConfig) DeepCopyInto(out *ScriptBootstrapActionConfig) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptBootstrapActionConfig.
func (in *ScriptBootstrapActionConfig) DeepCopy() *ScriptBootstrapActionConfig {
	if in == nil {
		return nil
	}
	out := new(ScriptBootstrapActionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfiguration) DeepCopyInto(out *SecurityConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfiguration.
func (in *SecurityConfiguration) DeepCopy() *SecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(SecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigurationList) DeepCopyInto(out *SecurityConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigurationList.
func (in *SecurityConfigurationList) DeepCopy() *SecurityConfigurationList {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigurationSpec) DeepCopyInto(out *SecurityConfigurationSpec) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigurationSpec.
func (in *SecurityConfigurationSpec) DeepCopy() *SecurityConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigurationStatus) DeepCopyInto(out *SecurityConfigurationStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigurationStatus.
func (in *SecurityConfigurationStatus) DeepCopy() *SecurityConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigurationSummary) DeepCopyInto(out *SecurityConfigurationSummary) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigurationSummary.
func (in *SecurityConfigurationSummary) DeepCopy() *SecurityConfigurationSummary {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigurationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EndedAt != nil {
		in, out := &in.EndedAt, &out.EndedAt
		*out = (*in).DeepCopy()
	}
	if in.IdleSince != nil {
		in, out := &in.IdleSince, &out.IdleSince
		*out = (*in).DeepCopy()
	}
	if in.ServerURL != nil {
		in, out := &in.ServerURL, &out.ServerURL
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.StateChangeReason != nil {
		in, out := &in.StateChangeReason, &out.StateChangeReason
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Session.
func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCloudWatchLoggingConfiguration) DeepCopyInto(out *SessionCloudWatchLoggingConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogGroup != nil {
		in, out := &in.LogGroup, &out.LogGroup
		*out = new(string)
		**out = **in
	}
	if in.LogStreamNamePrefix != nil {
		in, out := &in.LogStreamNamePrefix, &out.LogStreamNamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCloudWatchLoggingConfiguration.
func (in *SessionCloudWatchLoggingConfiguration) DeepCopy() *SessionCloudWatchLoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(SessionCloudWatchLoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionManagedLoggingConfiguration) DeepCopyInto(out *SessionManagedLoggingConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionManagedLoggingConfiguration.
func (in *SessionManagedLoggingConfiguration) DeepCopy() *SessionManagedLoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(SessionManagedLoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionMappingDetail) DeepCopyInto(out *SessionMappingDetail) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionMappingDetail.
func (in *SessionMappingDetail) DeepCopy() *SessionMappingDetail {
	if in == nil {
		return nil
	}
	out := new(SessionMappingDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionMappingSummary) DeepCopyInto(out *SessionMappingSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionMappingSummary.
func (in *SessionMappingSummary) DeepCopy() *SessionMappingSummary {
	if in == nil {
		return nil
	}
	out := new(SessionMappingSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionS3LoggingConfiguration) DeepCopyInto(out *SessionS3LoggingConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionS3LoggingConfiguration.
func (in *SessionS3LoggingConfiguration) DeepCopy() *SessionS3LoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(SessionS3LoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplifiedApplication) DeepCopyInto(out *SimplifiedApplication) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplifiedApplication.
func (in *SimplifiedApplication) DeepCopy() *SimplifiedApplication {
	if in == nil {
		return nil
	}
	out := new(SimplifiedApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepExecutionStatusDetail) DeepCopyInto(out *StepExecutionStatusDetail) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.LastStateChangeReason != nil {
		in, out := &in.LastStateChangeReason, &out.LastStateChangeReason
		*out = new(string)
		**out = **in
	}
	if in.StartDateTime != nil {
		in, out := &in.StartDateTime, &out.StartDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepExecutionStatusDetail.
func (in *StepExecutionStatusDetail) DeepCopy() *StepExecutionStatusDetail {
	if in == nil {
		return nil
	}
	out := new(StepExecutionStatusDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepStateChangeReason) DeepCopyInto(out *StepStateChangeReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepStateChangeReason.
func (in *StepStateChangeReason) DeepCopy() *StepStateChangeReason {
	if in == nil {
		return nil
	}
	out := new(StepStateChangeReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepSummary) DeepCopyInto(out *StepSummary) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepSummary.
func (in *StepSummary) DeepCopy() *StepSummary {
	if in == nil {
		return nil
	}
	out := new(StepSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepTimeline) DeepCopyInto(out *StepTimeline) {
	*out = *in
	if in.CreationDateTime != nil {
		in, out := &in.CreationDateTime, &out.CreationDateTime
		*out = (*in).DeepCopy()
	}
	if in.EndDateTime != nil {
		in, out := &in.EndDateTime, &out.EndDateTime
		*out = (*in).DeepCopy()
	}
	if in.StartDateTime != nil {
		in, out := &in.StartDateTime, &out.StartDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepTimeline.
func (in *StepTimeline) DeepCopy() *StepTimeline {
	if in == nil {
		return nil
	}
	out := new(StepTimeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Studio) DeepCopyInto(out *Studio) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.DefaultS3Location != nil {
		in, out := &in.DefaultS3Location, &out.DefaultS3Location
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.IDpAuthURL != nil {
		in, out := &in.IDpAuthURL, &out.IDpAuthURL
		*out = new(string)
		**out = **in
	}
	if in.ServiceRole != nil {
		in, out := &in.ServiceRole, &out.ServiceRole
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UserRole != nil {
		in, out := &in.UserRole, &out.UserRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Studio.
func (in *Studio) DeepCopy() *Studio {
	if in == nil {
		return nil
	}
	out := new(Studio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioSummary) DeepCopyInto(out *StudioSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudioSummary.
func (in *StudioSummary) DeepCopy() *StudioSummary {
	if in == nil {
		return nil
	}
	out := new(StudioSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportedInstanceType) DeepCopyInto(out *SupportedInstanceType) {
	*out = *in
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
	if in.InstanceFamilyID != nil {
		in, out := &in.InstanceFamilyID, &out.InstanceFamilyID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportedInstanceType.
func (in *SupportedInstanceType) DeepCopy() *SupportedInstanceType {
	if in == nil {
		return nil
	}
	out := new(SupportedInstanceType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpecification) DeepCopyInto(out *VolumeSpecification) {
	*out = *in
	if in.VolumeType != nil {
		in, out := &in.VolumeType, &out.VolumeType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpecification.
func (in *VolumeSpecification) DeepCopy() *VolumeSpecification {
	if in == nil {
		return nil
	}
	out := new(VolumeSpecification)
	in.DeepCopyInto(out)
	return out
}
